version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    command:
      - echo Build started on `date`
      - mvn package
artifacts:
  files:
    - 'target/webapp.war'
  discard-paths: yes