version: 0.2

phases:
  build:
    command:
      - echo Build started on `date`
      - mvn test
  post_build:
    command:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/web.war
    - webapp/*
    - maven-archiver/*
    - surefire/*